# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

addons:
  apt:
    packages:
    - gsl-bin
    - libgsl0ldbl
    - libgsl0-dev
    - libgsl2

r_packages:
  - covr
  - roxygen2

after_success:
  - Rscript -e 'library(covr); codecov()'
