# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
    - gsl-bin
    - libgsl0ldbl
    - libgsl0-dev

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
